### ISSUE TITLE
use gphoto for calibration

### ISSUE THREAD

**Issue by Leptopoda** [standupmaths/xmastree2020#30]
gphoto is a great CLI tool for controlling DSLRs. It currently has support for around 2700 models according to their [website](http://gphoto.org/).

This could be used for the first calibration/initialisation instead of the webcam potentially getting better results because:
- higher resolution
- fixed on a trypod
- clearer image by setting aperture, speed and ISO manually

I wated to implement this in the holidays but there was too much stuff regarding university.
I might have a look another time but thought I might share this idea 

EDIT: sadly it seems like the part calculating the coordinates and exporting them to the coordinates.txt is not in this repo :(

**Comment by oliverdunk** [comment]
Hi @Leptopoda - as you mentioned, the coordinate calculation code isn't in here. I think that's probably because it falls under the list of things too specific to Matt's setup to be easily shared!

That said, if you wanted to work on something like this, I think it'd make a nice addition to the "Further work" section of the README!

Going to close this one since it isn't an "issue" per say, but excited to see any progress! Totally understand if you don't find the time, of course.
